openapi: 3.0.1
info:
  title: WigeDev-Fitness-Log-Server
  description: WFL API Server
  version: 0.0.1
servers:
  - url: http://localhost:3000
    description: Local environment
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ServerMessage"
            type: string
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ServerMessage"
            type: string
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ServerMessage"
            type: string
    Deleted:
      description: Rows Deleted
      content:
        application/json:
          schema:
            type: object
            properties:
              deleted:
                type: string
                description: The number of rows that were deleted
  schemas:
    ServerMessage:
      type: object
      properties:
        message:
          type: string
    Role:
      type: string
      enum: [none, free, pro]
    Cycle:
      type: object
      properties:
          id:
            type: integer
          name:
            type: string
          modified:
            type: string
          workoutCount:
            type: integer
    Workout:
      type: object
      properties:
        date:
          type: string
        setCount:
          type: integer
    Exercise:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          nullable: true
    WorkoutDetail:
      type: object
      properties:
        date:
          type: string
        sets:
          type: array
          items:
            $ref: '#/components/schemas/Set'
    Set:
      type: object
      properties:
        id:
          type: integer
        exercise:
          $ref: '#/components/schemas/Exercise'
        weight:
          type: integer
        unit:
          type: string
        repsPrescribed:
          type: integer
        repsPerformed:
          type: integer
          nullable: true
  parameters:
    filterParam:
      in: query
      name: filter
      required: false
      schema:
        type: string
      description: Search text to filter the result set by
paths:
  /v1/signin:
    post:
      description: |
        Generates a JWT, given correct credentials.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200': # Response
          description: OK
          content: 
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                description: JWT token that contains userId as subject, email and role as data payload
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /v1/signup:
    post:
      description: |
        creates a WFL account and begins the em ail verification process.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                accountType:
                  type: string
              required:
                - email
                - password
                - accountType
      responses:
        '201': # Response
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                description: Returns the email address that the verification email was sent to.
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /v1/cycles:
    get:
      description: Returns cycles associated with the authenticated user.
      security:
        - bearerAuth: []
      responses:
        '200': # Response
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  cycles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Cycle'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      description: Creates a new cycle
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200': # Response
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cycle'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /v1/cycle/{id}:
    get:
      description: Reads the specified Cycle
      security:
        - bearerAuth: []
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: The ID of the Cycle being read.
      responses:
        '200': # Response
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cycle'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      description: Updates the specified Cycle
      security:
        - bearerAuth: []
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: The ID of the Cycle being updated
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200': # Response
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cycle'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      description: Deletes the specified Cycle
      security:
        - bearerAuth: []
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: The ID of the Cycle being deleted
      responses:
        '200': # Response
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Deleted'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /v1/workouts:
    get:
      description: Returns workouts associated with a given cycle
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: cycle
          schema:
            type: integer
          description: The cycle ID of the workouts requested
      responses:
        '200': # Response
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  workouts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Workout'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      description: Create a new workout
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkoutDetail'
      responses:
        '200': # Response
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutDetail'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /v1/workout/{date}:
    get:
      description: Returns the workout associated with the specified date if it exists
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: date
          required: true
          description: Date of the workout
          schema:
            type: string
      responses:
        '200': # Response
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  date:
                    type: string
                  sets:
                    type: array
                    items:
                      $ref: '#/components/schemas/Set'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      description: Updates the properties of a workout associated with the specified date
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: date
          required: true
          description: Date of the workout
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sets:
                  type: array
                  items:
                    $ref: '#/components/schemas/Set'
      responses:
        '200': # Response
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutDetail'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    