version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - vi-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM Packages
          command: |
            npm ci
      - save_cache:
          key: vi-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Style Check
          command: |
            npm run style
      - run:
          name: Lint Check
          command: |
            npm run lint
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Unit Tests
          command: |
            npm run test